kind: Pod
apiVersion: v1
metadata:
  name: login-test
  namespace: vault
spec:
  restartPolicy: Always
  serviceAccountName: backup-job
  containers:
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: toolbox
      command:
        - sleep
        - 'inf'
      securityContext:
        capabilities:
          drop:
            - MKNOD
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: snapshots
          mountPath: /snapshots
        - name: backup-job
          mountPath: /backup-job
      terminationMessagePolicy: File
      image: 'ghcr.io/dystewart/vault-k8s-login:latest'
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: mc
      command:
        - sleep
        - '36000'
      securityContext:
        capabilities:
          drop:
            - MKNOD
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: snapshots
          mountPath: /snapshots
        - name: backup-job
          mountPath: /backup-job
      terminationMessagePolicy: File
      image: 'quay.io/operate-first/mc:RELEASE.2022-06-17T02-52-50Z'
  serviceAccount: backup-job
  volumes:
    - name: snapshots
      persistentVolumeClaim:
        claimName: vault-snapshots
    - name: backup-job
      secret:
        secretName: vault-backup-s3-endpoint
        defaultMode: 420