name: publish

on: 
  push:
    branches:
       - main
    paths:
       - /vault-k8s-login/Dockerfile
  workflow_dispatch:     

jobs:
  publish-vault-k8s-login:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUBLISH_SECRET }}
      - name: Build the Docker image
        run: |
         docker build ./vault-k8s-login/ --tag ghcr.io/dystewart/vault-k8s-login:latest
         docker push ghcr.io/dystewart/vault-k8s-login:latest
